/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithmen.main;

import Algorithmen.data.Student;
import Algorithmen.comparator.Comparator;
import Algorithmen.hash.Hash;
import Algorithmen.menu.Menu;
import Algorithmen.probing.QuadraticProbing;
import Algorithmen.sort.Sortable;

public class App {
    public static Student[] getListOfStudents() {
        Student[] students = new Student[6];
        students[0] = new Student("Watson", "John", 1, 3568);
        students[1] = new Student("Holmes", "Sherlock", 5, 7629);
        students[2] = new Student("Moriarty", "Jim", 3, 4321);
        students[3] = new Student("Hooper", "Molly", 2, 1562);
        students[4] = new Student("Watson", "Mary", 4, 2690);
        students[5] = new Student("Lestrade", "Greg", 6, 4527);
        return students;
    }

    public static void print(Student[] students) {
        for (int i = 0; i < students.length; i++) {
            System.out.println((i + 1) + ". " + students[i]);
        }
    }

    public static void sortAndPrint(Student[] students, Sortable<Student> algorithm, Comparator<Student> comparator) {
        System.out.println("Sort algorithm: " + algorithm.getClass().getSimpleName() + "  Comparator: " + comparator.getClass().getSimpleName());
        algorithm.sort(students, comparator);
        print(students);
        System.out.println();
    }

    public static void main(String[] args) {
        int m = 8;
        ADSHashTable table = new ADSHashTable(m, new Hash(m), new QuadraticProbing());
        System.out.println();
        System.out.println("Console-Application: Exercise-5             <Ekaterina><Krysenkova><573734>");
        Menu.choice(table);
    }
}